name: muslimmovie
description: Bismillah
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.1.1
  concentric_transition: ^1.0.3
  lottie: ^2.0.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.2
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true





  assets:
    - assets/anim/
    - assets/img/
